spring.application.name=api-gateway
server.port=8080

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

jwt.secret=9a618c6d48fed2c7482a13876e5ff909192484ab9f4a7c29e248ab4c19a28b12

# Spring Cloud Gateway Routes using Eureka Service Discovery
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Custom Route Rules
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**

spring.cloud.gateway.routes[1].id=customer-service
spring.cloud.gateway.routes[1].uri=lb://CUSTOMER-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/customers/**

spring.cloud.gateway.routes[2].id=merchant-service
spring.cloud.gateway.routes[2].uri=lb://MERCHANT-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/merchants/**

spring.cloud.gateway.routes[3].id=subscription-service
spring.cloud.gateway.routes[3].uri=lb://SUBSCRIPTION-SERVICE
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/subscriptions/**

spring.cloud.gateway.routes[4].id=payment-service
spring.cloud.gateway.routes[4].uri=lb://PAYMENT-SERVICE
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/payments/**

spring.cloud.gateway.routes[5].id=coupon-service
spring.cloud.gateway.routes[5].uri=lb://COUPON-SERVICE
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/coupons/**

spring.cloud.gateway.routes[6].id=redemption-service
spring.cloud.gateway.routes[6].uri=lb://REDEMPTION-SERVICE
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/redemptions/**

spring.cloud.gateway.routes[7].id=cashback-service
spring.cloud.gateway.routes[7].uri=lb://CASHBACK-SERVICE
spring.cloud.gateway.routes[7].predicates[0]=Path=/api/cashback/**

spring.cloud.gateway.routes[8].id=points-service
spring.cloud.gateway.routes[8].uri=lb://CASHBACK-SERVICE
spring.cloud.gateway.routes[8].predicates[0]=Path=/api/points/**

spring.cloud.gateway.routes[9].id=admin-service
spring.cloud.gateway.routes[9].uri=lb://ADMIN-SERVICE
spring.cloud.gateway.routes[9].predicates[0]=Path=/api/admin/**

spring.cloud.gateway.routes[10].id=notification-service
spring.cloud.gateway.routes[10].uri=lb://NOTIFICATION-SERVICE
spring.cloud.gateway.routes[10].predicates[0]=Path=/api/notifications/**

spring.cloud.gateway.routes[11].id=merchant-alert-service
spring.cloud.gateway.routes[11].uri=lb://MERCHANT-ALERT-SERVICE
spring.cloud.gateway.routes[11].predicates[0]=Path=/api/merchant-alerts/**

management.endpoints.web.exposure.include=health,info,gateway
