spring.application.name=redemption-service
server.port=8087

spring.datasource.url=jdbc:mysql://localhost:3306/redemption_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Logesh@2005
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

rabbitmq.exchange.redemption=deals.redemption.exchange
rabbitmq.routingkey.coupon-redeemed=coupon.redeemed

# Resilience4j Circuit Breaker Config for Coupon & Merchant Services
resilience4j.circuitbreaker.instances.couponService.sliding-window-size=5
resilience4j.circuitbreaker.instances.couponService.minimum-number-of-calls=3
resilience4j.circuitbreaker.instances.couponService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.couponService.wait-duration-in-open-state=5s
resilience4j.circuitbreaker.instances.couponService.permitted-number-of-calls-in-half-open-state=2

resilience4j.circuitbreaker.instances.merchantService.sliding-window-size=5
resilience4j.circuitbreaker.instances.merchantService.minimum-number-of-calls=3
resilience4j.circuitbreaker.instances.merchantService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.merchantService.wait-duration-in-open-state=5s
resilience4j.circuitbreaker.instances.merchantService.permitted-number-of-calls-in-half-open-state=2

# Resilience4j Retry Config
resilience4j.retry.instances.couponService.max-attempts=3
resilience4j.retry.instances.couponService.wait-duration=500ms

resilience4j.retry.instances.merchantService.max-attempts=3
resilience4j.retry.instances.merchantService.wait-duration=500ms

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

management.endpoints.web.exposure.include=health,info,circuitbreakers
