# Global Defaults across all services
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

jwt.secret=9a618c6d48fed2c7482a13876e5ff909192484ab9f4a7c29e248ab4c19a28b12
jwt.expirationMs=86400000

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
